version: '2.4'

networks:
  default:
    name: neo_go_network
    ipam:
      config:
        - subnet: 172.200.0.0/24
          gateway: 172.200.0.254

services:
  node:
    labels:
      - stats
    image: registry.nspcc.ru/neo-bench/neo-sharp:bench
    logging:
      driver: $NEOBENCH_LOGGER
    stdin_open: true
    tty: true
    ports: [ "20331:20331" ]
    environment:
      - ACC=single.acc
    volumes:
      - ./wallet.one.json:/neo-cli/wallet.json
      - ./sharp.config.single.json:/neo-cli/config.json
    healthcheck:
      interval: 5s
      retries: 50
      test: ['CMD', 'bash', '-c', '/healthcheck.sh']
      timeout: 10s

  healthy:
    image: alpine
    depends_on:
      node:
        condition: service_healthy
