version: '2.4'

networks:
  default:
    name: neo_go_network
    ipam:
      config:
        - subnet: 172.200.0.0/24
          gateway: 172.200.0.254

services:
  node_one:
    labels:
      - stats
    container_name: neo_go_node_one
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: $NEOBENCH_LOGGER
    cap_add:
      - NET_ADMIN
    command: "node --config-path /config --privnet"
    expose: [ "30333" ]
    healthcheck:
      interval: 5s
      retries: 15
      test: ['CMD', 'sh', '-c', 'echo | nc 127.0.0.1 30333']
      timeout: 10s
    environment:
      - ACC=dump.acc
      - NEOBENCH_TC=$NEOBENCH_TC
    volumes:
      - ./wallet.one.json:/config/wallet.json
      - ./go.protocol.privnet.one.yml:/config/protocol.privnet.yml

  node_two:
    labels:
      - stats
    container_name: neo_go_node_two
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: $NEOBENCH_LOGGER
    cap_add:
      - NET_ADMIN
    command: "node --config-path /config --privnet"
    expose: [ "30334" ]
    healthcheck:
      interval: 5s
      retries: 15
      test: ['CMD', 'sh', '-c', 'echo | nc 127.0.0.1 30334']
      timeout: 10s
    environment:
      - ACC=dump.acc
      - NEOBENCH_TC=$NEOBENCH_TC
    volumes:
      - ./wallet.two.json:/config/wallet.json
      - ./go.protocol.privnet.two.yml:/config/protocol.privnet.yml

  node_three:
    labels:
      - stats
    container_name: neo_go_node_three
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: $NEOBENCH_LOGGER
    cap_add:
      - NET_ADMIN
    command: "node --config-path /config --privnet"
    expose: [ "30335" ]
    healthcheck:
      interval: 5s
      retries: 15
      test: ['CMD', 'sh', '-c', 'echo | nc 127.0.0.1 30335']
      timeout: 10s
    environment:
      - ACC=dump.acc
      - NEOBENCH_TC=$NEOBENCH_TC
    volumes:
      - ./wallet.three.json:/config/wallet.json
      - ./go.protocol.privnet.three.yml:/config/protocol.privnet.yml

  node_four:
    labels:
      - stats
    container_name: neo_go_node_four
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: $NEOBENCH_LOGGER
    cap_add:
      - NET_ADMIN
    command: "node --config-path /config --privnet"
    expose: [ "30336" ]
    healthcheck:
      interval: 5s
      retries: 15
      test: ['CMD', 'sh', '-c', 'echo | nc 127.0.0.1 30336']
      timeout: 10s
    environment:
      - ACC=dump.acc
      - NEOBENCH_TC=$NEOBENCH_TC
    volumes:
      - ./wallet.four.json:/config/wallet.json
      - ./go.protocol.privnet.four.yml:/config/protocol.privnet.yml

  healthy:
    image: alpine
    depends_on:
      node_one:
        condition: service_healthy
      node_two:
        condition: service_healthy
      node_three:
        condition: service_healthy
      node_four:
        condition: service_healthy
