version: '2.4'

networks:
  default:
    name: neo_go_network
    ipam:
      config:
        - subnet: 172.200.0.0/24
          gateway: 172.200.0.254

services:
  node_one:
    labels:
      - stats
    image: registry.nspcc.ru/neo-bench/neo-sharp:bench
    logging:
      driver: $NEOBENCH_LOGGER
    cap_add:
      - NET_ADMIN
    container_name: neo-cli-node-one
    stdin_open: true
    tty: true
    volumes:
      - ./wallet.one.json:/neo-cli/wallet.json
      - ./sharp.config.one.json:/neo-cli/config.json
    healthcheck:
      interval: 5s
      retries: 50
      test: ['CMD', 'bash', '-c', '/healthcheck.sh']
      timeout: 10s
    environment:
      - ACC=dump.acc
      - NEOBENCH_TC=$NEOBENCH_TC

  node_two:
    labels:
      - stats
    image: registry.nspcc.ru/neo-bench/neo-sharp:bench
    logging:
      driver: $NEOBENCH_LOGGER
    cap_add:
      - NET_ADMIN
    container_name: neo-cli-node-two
    stdin_open: true
    tty: true
    volumes:
      - ./wallet.two.json:/neo-cli/wallet.json
      - ./sharp.config.two.json:/neo-cli/config.json
    healthcheck:
      interval: 5s
      retries: 50
      test: ['CMD', 'bash', '-c', '/healthcheck.sh']
      timeout: 10s
    environment:
      - ACC=dump.acc
      - NEOBENCH_TC=$NEOBENCH_TC

  node_three:
    labels:
      - stats
    image: registry.nspcc.ru/neo-bench/neo-sharp:bench
    logging:
      driver: $NEOBENCH_LOGGER
    cap_add:
      - NET_ADMIN
    container_name: neo-cli-node-three
    stdin_open: true
    tty: true
    volumes:
      - ./wallet.three.json:/neo-cli/wallet.json
      - ./sharp.config.three.json:/neo-cli/config.json
    healthcheck:
      interval: 5s
      retries: 50
      test: ['CMD', 'bash', '-c', '/healthcheck.sh']
      timeout: 10s
    environment:
      - ACC=dump.acc
      - NEOBENCH_TC=$NEOBENCH_TC

  node_four:
    labels:
      - stats
    image: registry.nspcc.ru/neo-bench/neo-sharp:bench
    logging:
      driver: $NEOBENCH_LOGGER
    cap_add:
      - NET_ADMIN
    container_name: neo-cli-node-four
    stdin_open: true
    tty: true
    volumes:
      - ./wallet.four.json:/neo-cli/wallet.json
      - ./sharp.config.four.json:/neo-cli/config.json
    healthcheck:
      interval: 5s
      retries: 50
      test: ['CMD', 'bash', '-c', '/healthcheck.sh']
      timeout: 10s
    environment:
      - ACC=dump.acc
      - NEOBENCH_TC=$NEOBENCH_TC

  healthy:
    image: alpine
    depends_on:
      node_one:
        condition: service_healthy
      node_two:
        condition: service_healthy
      node_three:
        condition: service_healthy
      node_four:
        condition: service_healthy
